name: deploy-gh-pages

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: false  
        fetch-depth: 0    

    - name: clone submodule
      uses: actions/checkout@v2
      with:
        repository: antonioalmeida/tex-hugo-theme
        path: quickstart/themes/tex
        ssh-key: ${{ secrets.SSH_KEY }}
        persist-credentials: true

    - name: checkout submodule
      run: |
        git submodule init
        git submodule update

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.75.1'

    - name: Build
      working-directory: quickstart
      run: hugo --minify

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: quickstart/public
        CLEAN: true  


        